config/routes.rb
Rails.application.routes.draw do

  root to: 'welcome#index'

  resources :welcome do
    collection do
      get :srt_doc_landing
      get :pdf_txt_3_landing
      get :pdf_rows_3_landing
      get :xlsx_txt_amedia_landing
      post :srt_to_doc
      post :pdf_txt_cont_parse
      post :pdf_rows_cont_parse
      post :xlsx_txt_amedia_parse
      get :karakal_doc, format: 'docx'
      get :colorify_doc
    end
  end

  resources :colorifys do
    put :update_car, format: 'docx'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/doc.rb
class Doc < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/colorifys_controller.rb
class ColorifysController < ApplicationController

  def new
  end

  def show
    @doc = Doc.find(params[:id])
  end

  def update_car
    doc = Doc.find(params[:colorify_id])
    @doc_datas = doc.doc_data['doc_data']
    docx = Caracal::Document.new('example_document1.docx')

    respond_to do |format|
      format.docx { headers["Content-Disposition"] = "attachment; filename=\"#{doc.doc_data['filename']}\"" }
    end
  end

  def create
    doc = Docx::Document.open(params[:docx])
    doc_data = []
    character = false
    characters = []

    doc.tables[0].columns.each do |column| # Column-based iteration
      column.cells.each do |cell|
        character = true if cell.text == 'Персонаж'
        character = false if cell.text == 'Timecode' || cell.text == 'Текст'

        if character
          characters << cell.text if characters.exclude?(cell.text)
        end
      end
    end

    doc.tables.each do |table|
      table.rows.each do |row| # Row-based iteration
        row_data = []
        row.cells.each do |cell|
          row_data << cell.text
        end
        doc_data << row_data
      end
    end

    doc = Doc.create(doc_data: {filename: params[:docx].original_filename, doc_data: doc_data }, characters_data: {characters: characters} )

    redirect_to colorify_path(doc)
  end
end

app/controllers/parsers_controller.rb
class ParsersController < ApplicationController

  def srt_to_doc

  end
end

app/controllers/welcome_controller.rb
require 'pdf/reader'

class WelcomeController < ApplicationController

  def index; end
  def srt_doc_landing; end
  def pdf_txt_3_landing; end
  def pdf_rows_3_landing; end
  def pdf_txt_hbo_landing; end
  def xlsx_txt_amedia_landing; end


  def srt_to_doc
    tmp = params[:srt].tempfile

    ary = []

    File.new(tmp).each_with_index do |line, index|
      next if index == 0
      qw = line.strip
      matching =
          if qw.match(/-->/).present?
            arr = qw.split('-->').first.split(':')
            "#{arr[1]}:#{arr[2].split(',').first}"

          elsif !/\A\d+\z/.match(qw)
            qw
          end

      ary << matching if matching.present?
    end

    target = ary.in_groups_of(3)

    doc = Doc.create(doc_data: { srt_data: target.unshift(["Timecode", "Character", "Dialogue"]) } )

    cookies[:doc_id] = doc.id

    redirect_to karakal_doc_welcome_index_path
  end

  def karakal_doc
    rec = Doc.find(cookies[:doc_id])
    @srt_data = rec.doc_data['srt_data']

    respond_to do |format|
      format.docx { headers["Content-Disposition"] = "attachment; filename=\"caracal1.docx\"" }
    end
  end

  def pdf_txt_cont_parse
    tmp = params[:pdf].tempfile
    reader = PDF::Reader.new(tmp)
    is_script_begin = false
    path = "public/#{params[:pdf].original_filename.split('.').first}.txt"
    f = File.new(path, 'w')
    reader.pages.each do |page|
      page.text.each_line do |line|
        str = line.chomp.squeeze(" ")
        timecode = str[/(?:[01]\d|2[0-3]):(?:[0-5]\d):(?:[0-5]\d):(?:[0-5]\d)/]
        character = str[/(?<!\[)\b[A-Z][A-Z]+\b(?![\w\s]*[\]])/]
        dialogue = str.gsub(/(?:[01]\d|2[0-3]):(?:[0-5]\d):(?:[0-5]\d):(?:[0-5]\d)|(?<!\[)\b[A-Z][A-Z]+\b(?![\w\s]*[\]])/, '')

        if dialogue == ' Timecode Character Dialogue Translation'
          is_script_begin = true
          next
        end

        next unless is_script_begin

        if timecode.present?
          ary = timecode.split(':')
          normalized_timecode = "#{ary[1]}:#{ary[2]}"

          f.write("#{normalized_timecode.chomp.strip}\n")
        end

        f.write("#{character.chomp.strip}\n") if character.present? && character.length > 1
        f.write("#{dialogue.chomp.strip}\n") if dialogue.present?
      end
    end

    f.close

    file = f.path
    File.open(file, 'r') do |f|
      send_data f.read.force_encoding('BINARY'), :filename => "#{params[:pdf].original_filename.split('.').first}.txt", :disposition => "attachment"
    end
    File.delete(file)
  end

  def xlsx_txt_amedia_parse
    tmp = params[:xls].tempfile
    xlsx = Roo::Spreadsheet.open(tmp)
    path = "public/#{params[:xls].original_filename.split('.').first}.txt"
    f = File.new(path, 'w')

    xlsx.each_with_pagename do |name, sheet|
      sheet.each do |ary|
        next if ary.first == sheet.row(1).first
        next if ary.first.blank?
        next if ary[3].blank?

        timecode = ary.first
        character = ary[2]
        dialogue = ary[3]

        if timecode.present?
          ary = timecode.split(':')
          normalized_timecode = "#{ary[1]}:#{ary[2]}"

          f.write("#{normalized_timecode.chomp.strip}\n")
        end

        if character.present?
          normalized_character = character.split.first

          f.write("#{normalized_character.chomp.strip}\n")
        end

        if dialogue.present?
          dialogue = dialogue.gsub(/\r|\n|\t/,'')
          dialogue = dialogue.gsub(/\b[A-Z][A-Z]+\b/, &:downcase)

          f.write("#{dialogue.chomp.strip}\n")
        end
      end
    end

    f.close

    file = f.path
    File.open(file, 'r') do |f|
      send_data f.read.force_encoding('BINARY'), :filename => "#{params[:xls].original_filename.split('.').first}.txt", :disposition => "attachment"
    end
    File.delete(file)
  end



  def pdf_rows_cont_parse
    tmp = params[:pdf].tempfile
    reader = PDF::Reader.new(tmp)
    path = "public/#{params[:pdf].original_filename.split('.').first}.txt"
    f = File.new(path, 'w')
    reader.pages.each do |page|
      page.text.each_line do |line|
        next if page.number == 1
        str = line.chomp.squeeze(" ")

        timecode = str[/(?:[01]\d|2[0-3]):(?:[0-5]\d):(?:[0-5]\d):(?:[0-5]\d)/]


        str2 = str.gsub(/(?:[01]\d|2[0-3]):(?:[0-5]\d):(?:[0-5]\d):(?:[0-5]\d)/, '')

        if str.present?
          next if str.match(/Page/).present?

          if timecode.present?
            ary = timecode.split(':')
            normalized_timecode = "#{ary[1]}:#{ary[2]}"

            f.write("#{normalized_timecode.chomp.strip}\n")
          end

          f.write("#{str2.chomp.strip}\n")
        end
      end
    end

    f.close

    file = f.path
    File.open(file, 'r') do |f|
      send_data f.read.force_encoding('BINARY'), :filename => "#{params[:pdf].original_filename.split('.').first}.txt", :disposition => "attachment"
    end
    File.delete(file)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/colorifys/new.html.erb
<div class="container">
  <div class="qwe">Upload Doc file</div>
  <p></p>
  <%= form_with url: colorifys_path do |f| %>
    <%= f.file_field :docx %>
    <%= f.submit 'upload' %>
  <% end %>
</div>

app/views/colorifys/show.html.erb
<div class="container">
  <%= form_with url: colorify_update_car_path(@doc.id), method: :put do |f| %>
    <% @doc.characters_data['characters'].each do |character| %>
      <div class="mb-2">
        <%= f.color_field "color[#{character}]", class: 'form-control-color', value: '#ffffff' %>
        <%= f.label character %>
      </div>
    <% end %>
    <div class="mt-4">
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dishwasher</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<div class="qwe">
  <%= link_to 'SRT to Doc', srt_doc_landing_welcome_index_path %>
</div>

<p></p>

<div class="qwe">
  <%= link_to 'PDF 3 to txt', pdf_txt_3_landing_welcome_index_path %>
</div>

<p></p>

<div class="qwe">
  <%= link_to 'xlsx to txt(amedia)', xlsx_txt_amedia_landing_welcome_index_path %>
</div>

<p></p>

<div class="qwe">
  <%= link_to 'PDF rows to txt', pdf_rows_3_landing_welcome_index_path %>
</div>

<p></p>

<div class="qwe">
  <%= link_to 'Colorify Doc', new_colorify_path %>
</div>

app/views/welcome/pdf_rows_3_landing.html.erb
<div class="qwe">PDF rows to txt</div>
<p></p>
<%= form_with url: pdf_rows_cont_parse_welcome_index_path do |f| %>
  <%= f.file_field :pdf %>
  <%= f.submit %>
<% end %>

app/views/welcome/pdf_txt_3_landing.html.erb
<div class="qwe">PDF 3 to txt</div>
<p></p>
<%= form_with url: pdf_txt_cont_parse_welcome_index_path do |f| %>
  <%= f.file_field :pdf %>
  <%= f.submit %>
<% end %>

app/views/welcome/pdf_txt_cont_landing.html.erb
<div class="qwe">PDF to txt(contentica)</div>
<p></p>
<%= form_with url: pdf_txt_cont_parse_welcome_index_path do |f| %>
  <%= f.file_field :pdf %>
  <%= f.submit %>
<% end %>

app/views/welcome/srt_doc_landing.html.erb
<div class="qwe">SRT to Doc</div>
<p></p>
<%= form_with url: srt_to_doc_welcome_index_path do |f| %>
  <%= f.file_field :srt %>
  <%= f.submit %>
<% end %>

app/views/welcome/xlsx_txt_amedia_landing.html.erb
<div class="qwe">xlsx to txt(amedia)</div>
<p></p>
<%= form_with url: xlsx_txt_amedia_parse_welcome_index_path do |f| %>
  <%= f.file_field :xls %>
  <%= f.submit %>
<% end %>